
services:
  elasticsearch:
    image: elasticsearch:8.14.0
    container_name: es-for-darknet-project
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 12
    networks:
      - elastic-net
  kibana: 
    image: kibana:8.14.0 
    container_name: kibana-for-darknet-project
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 
      - I18N_LOCALE=zh-CN
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks: 
      - elastic-net
volumes:
  es_data:
    driver: local

networks: 
  elastic-net:
    driver: bridge